name = "telegram-microblogging-bot"
main = "src/index.ts"
compatibility_date = "2026-03-01"

[[kv_namespaces]]
binding = "MEDIA_GROUPS"
id = "1bf500c967b84fedafbd07bf6463e96c"

[vars]
GITHUB_REPO = "benediktweishaupt/elternzeitreise-blog"

# Secrets (set via `wrangler secret put`):
# TELEGRAM_BOT_TOKEN
# TELEGRAM_WEBHOOK_SECRET
# GITHUB_TOKEN
# BENE_TELEGRAM_ID
# SANDRA_TELEGRAM_ID
